---
title: "Portfolio Planning Part 1"
format: html
---

## Describing data

1.  The first data set is from Cal Recycle and is the Multi-Year County Wide Origin Summary for Monterey. It is found at <https://www2.calrecycle.ca.gov/LGCentral/DisposalReporting/Origin/CountywideSummary> on Cal Recycle's website. This data is called `CountywideSummary.xlsx`

    The second data source (broken in to two tables) is from the US Census Bureau QuickFacts table. It contains some estimates from vintage year 2024 and 2025 other years date back to 2010. The Census data is from the 2010 Census of Population and Housing and the 2020 Census fo Population and Housing. Other data comes from a variety of sources. All data was accessed on March 22, 2026. It can be found at <https://www.census.gov/quickfacts/fact/table/pacificgrovecitycalifornia,montereycitycalifornia,marinacitycalifornia,kingcitynorthcarolina,greenfieldcitycalifornia,gonzalescitycalifornia/PST045224> and <https://www.census.gov/quickfacts/fact/table/soledadcitycalifornia,seasidecitycalifornia,salinascitycalifornia/PST045224>. This data is called `QuickFacts Mar-22-2026 (1).csv` and `QuickFacts Mar-22-2026.csv`

2.  The first data set, a county wide recycling summary for Monterey county contains the variables Report Year; Report Quarter, which lists each of the four quarters of the year and is broken down in to cities with in Monterey county; Disposal Ton, the amount of waste produced within a city within that time period; Export Ton; Transformation Ton; and Total ADC, ADC stands for alternate daily cover which is material other than soil used to cover a landfill.

    The Second data set contains a variety of infromation on people, businesses and geography of cities over 5,000 people in Monterey County, CA. The variables are Fact, which contains the name of the statistic listed; Fact Note; city name for each city, which contains the value for the respective fact; and Value Note for each city.
    
3. Question 1: How does population size of a city, for cities over 5000 people, affect waste generation per person in Monterey county?

    Question 2: How does population size per square mile affect waste generation per person for cities over 5000 people in Monterey County?

    Question 3: How has waste generation changed from 1995 in Monterey County?

## Data Visulization

1. For my final visualizations I would like a scatter plot of population on the x axis and waste generation per person on the y axis and each point labeled by the city it represents for questions 1 and 2. For question 3 I want my final visualization to be a line graph with year on the x axis and waste generation on the y axis split up by city.

2. In order to answer my research questions I want to highlight how population size and density is, or is not, correlated to waste generation, trying to represent how rural, suburban, and urban areas differ in their waste generation. I want to emphasize the size of the city over the city name in my visualizations in order to answer these questions.

3. To make these visualizations I would need to reformat some of the data and calculate the waste generation per person.

## Data Cleaning

2. One piece of missing data is year, it is only placed in one row but corresponds to other rows that have NAs instead of year values.

4. I will need to create a new variable of waste generation per person. I will create this data set by combining population statistics from the second data set and waste generation statistics from the first data set. This will first require joining the two data sets.

5. I will need to join the two parts of the second data set together. They can be joined by the `Fact` row which they share. I will also need to join the waste generation data set and the population data set by city. To do this the both data sets will need to be pivoted to have a variable for city.

6. The second data set will need to be pivoted to make city a variable in order for it to be joined with the other data set. This would make the population facts also be variables. The first data set needs to be pivoted so that the Report Quarter column becomes two different columns, one for city and one for quarter.