---
title: "data-cleaning"
format: html
---

Data cleaning for portfolio project.

```{r}
#| label: setup
#| echo: false
#loading all required packages
library(tidyverse)
library(readxl)
```

```{r}
#| label: read-data
#reading in all data sets that will be used

waste_summary <- read_xlsx("data-raw/CountywideSummary.xlsx", skip = 3)

population_data_a <- read_csv("data-raw/QuickFacts Mar-22-2026.csv")

population_data_b <- read_csv("data-raw/QuickFacts Mar-22-2026 (1).csv")

```
## Cleaning Population Data

```{r}
#| label: creating-data-set-population
#creating a single population data set with all cites and only rows that may be later used for this project

population_data_1 <- population_data_a |>
  drop_na("Fact") |>
  left_join(population_data_b, "Fact") |>
  select(-contains("Note")) |>
  filter(Fact %in% c("Population, Census, April 1, 2010", "Population per square mile, 2010"))
```

Choosing to use data from 2010 census instead of 2020 census because 2010 is more in the middle of waste summary range.

```{r}
#| label: pivoting-population
#pivoting the data so that there is a city column that will match with the city column in the waste data set 

population_data_2 <- population_data_1 |> 
  pivot_longer(cols = -Fact, names_to = "city-ca", values_to = "value") |>
  pivot_wider(names_from = Fact, values_from = value) |>
  janitor::clean_names()
```

```{r}
#| label: adjusting-city-names-population
#making the city column have the same format for city names as the waste data set so that joining the data sets will be possible. This means removing the " city, California" 
population_data_3 <- population_data_2 |>
  mutate(city = str_sub(city_ca, end = -18)) |>
  select(-city_ca)
```

```{r}
#| label: making-cols-numeric-population
#also making the columns read as numbers to be able to do calculations with them later.
population_data_4 <- population_data_3 |>
  mutate(population_census_april_1_2010 = parse_number(population_census_april_1_2010), population_per_square_mile_2010 = parse_number(population_per_square_mile_2010))
```


## Cleaning Waste Data

```{r}
#| label: solving-nas-names-waste
#filling in the empty rows with the date because the date was only placed in one row and also cleaning the names to make it easier to work with

waste_summary_1 <- waste_summary |>
  select(1:3) |>
  fill(1) |>
  janitor::clean_names() |>
  rename(disposal_ton = diposal_ton)
#assuming spelling mistake in diposal and changing to disposal
```


```{r}
#| label: waste-quarter
#pulling the information on quarter out of column 2 and into a separate column

waste_summary_2 <- waste_summary_1 |>
  mutate(quarter = as.numeric(report_quarter)) |>
  fill(4)
```

```{r}
#| label: removing-extra-waste-col-2
#taking out the information that is stored under year and quarter but not linked to a specific city as it is not needed.
waste_summary_3 <- waste_summary_2 |>
  drop_na(report_quarter) |>
  filter(!report_quarter %in% c(1, 2, 3, 4)) |>
  rename(city = report_quarter)
```

```{r}
#| label: waste-year-quarter
#making the quarter and year column be combined so that they are one variable to make a continuous time scale that is able to be graphed. Graphing each quarter as the start of that quarter of a year.

waste_summary_4 <- waste_summary_3 |>
  mutate(time = report_year + ((quarter -1) / 4)) |>
  select(-report_year, -quarter)
# this is that data set that will be used for q3
```

All quarters are displayed as being at the start of that fourth of the year.

## Combining Data Sets

```{r}
#| label: combining-data-waste-population
#combining the two data sets for q1 and q2 with eventual goal of creating per population variable

waste_population_2010_city_over_5000_1 <- waste_summary_4 |>
  left_join(population_data_4, by = join_by(city)) |>
  drop_na(population_census_april_1_2010) 
```

```{r}
#| label: waste-population-creating-per-population-variable
#creating a variable that involves waste per population for q1 and q2

waste_population_2010_city_over_5000_2 <- waste_population_2010_city_over_5000_1 |>
  mutate(disposal_per_population_ton = (disposal_ton / population_census_april_1_2010))
```

## Writing Clean Data

```{r}
#| label: writing-data-1-2
#writing the data that will be used for questions 1 and 2
write_csv(waste_population_2010_city_over_5000_2, "data-clean/waste-population-q1-q2")
```

```{r}
#| label: writing-data-3
#writing the data that will be used to answer question 3, in the long data format to allow for the use of grouping.
write_csv(waste_summary_4, "data-clean/waste-summary-q3")
```